version: "3" # version of docker compose

services:
  nft-staker:
    build:
      context: ../
      dockerfile: ./docker_files/e2e.Dockerfile
      args:
        - HARDHAT_NETWORK=dockerhost
        - ETHERNAL_API_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJlYmFzZVVzZXJJZCI6InFJbzI1WkZhbXRPVk11WENvdzNWdTZRaDROaDIiLCJhcGlLZXkiOiJYMFc5RzNWLUhZRk02N0UtTlNUV0cyQy1NSlBSWFI3XHUwMDAxIiwiaWF0IjoxNzAyOTY2OTY0fQ.dp_l6cMt1c9ge4I1NSPwAXgQ8RtUZ4oFrPbRtVi4KlE
        - ETHERNAL_WORKSPACE=local_net_explorer

        - REACT_APP_IPFS_GATEWAY=http://127.0.0.1:4325/
        - REACT_APP_EVMCHAIN_HTTP_PROVIDER_URL_READONLY=http://127.0.0.1:8545/
    image: nft-staker-image:latest
    container_name: nft-staker-container
    hostname: nft-staker
    restart: "no"
    ports:
      - "8080:80"
